# BASIC INFORMATION
name: "mdx-embeddings-actions"
description: "Generate embeddings from your Knowledge Base to use with Vercel Postgres."
author: "PieterDePauw"

# GITHUB BRANDING
branding:
  icon: "heart"
  color: "red"

# INPUT VALUES
inputs:
  OPENAI_API_KEY:
    description: "OpenAI API Key"
    required: true
  DATABASE_URL:
    description: "Database URL"
    required: true
  DOCS_ROOT_PATH:
    description: "Path to the documentation directory"
    required: true
    default: "docs"

# RUNTIME CONFIGURATION
runs:
  using: "node20"
  main: "dist/index.js"
