# BASIC INFORMATION
name: "mdx-embeddings-actions"
description: "Generate embeddings from your Knowledge Base to use with Vercel Postgres."
author: "PieterDePauw"

# GITHUB BRANDING
branding:
  icon: "heart"
  color: "red"

# ENVIRONMENTAL VALUES
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  DOCS_ROOT_PATH: ${{ secrets.DOCS_ROOT_PATH }}
  DOCS_FULL_PATH: ${{ github.workspace }}/${{ secrets.DOCS_ROOT_PATH }}
  directory: ${{ github.workspace }}/docs

# INPUT VALUES
inputs:
  DATABASE_URL:
    required: true
    description: "Your Vercel Postgres database URL"
  OPENAI_API_KEY:
    required: true
    description: "Your OpenAI API key"
  DOCS_ROOT_PATH:
    required: true
    description: "The path to the root of your knowledge base or docs folder"
    default: "./docs"

# RUNTIME CONFIGURATION
runs:
  using: "node20"
  main: "dist/index.js"
