name: Generate Embeddings

on:
  push:
    branches:
      - main # or your default branch name
    paths:
      - "docs/**" # Adjust this to match your documentation directory

jobs:
  generate-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust this to match your preferred Node.js version

      - name: Install dependencies
        run: npm ci # or yarn install, depending on your package manager

      - name: Generate Embeddings
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          node -e "
          const { run } = require('./main');
          run().catch(error => {
            console.error(error);
            process.exit(1);
          });
          "
